### ISSUE TITLE
OS: Unknown issue 

### ISSUE THREAD

**Issue by voxie12** [Ruturajn/fetchit#1]
![2022-08-20-215309_948x513_scrot](https://user-images.githubusercontent.com/65469239/185765660-9d1055f5-de3a-4242-b2a6-1499db76fc6d.png)

**Comment by voxie12** [comment]
as well as session.

**Comment by Ruturajn** [comment]
Hi,
What OS and WM/DE are you using?

**Comment by voxie12** [comment]
arch linux and dwm

**Comment by Ruturajn** [comment]
Yeah, this is a bug, for the OS, entry. I am not sure, about the session though. I will look into it some more, and let you know.
Thanks

**Comment by voxie12** [comment]
no problems.

**Comment by Ruturajn** [comment]
The OS, issue should be fixed in the latest commit, you can try it out.

**Comment by voxie12** [comment]
![2022-08-20-224530_532x292_scrot](https://user-images.githubusercontent.com/65469239/185767045-9372f1ea-2f2d-457e-904d-8233075e783d.png)
the os works good

**Comment by Ruturajn** [comment]
Great. Actually, since `DWM` doesn't set the `XDG` session, environment variables, `fetchit` is not picking it up. I'll try to resolve this as soon as possible.

**Comment by voxie12** [comment]
thank you, awesome work btw!

**Comment by Ruturajn** [comment]
Thanks a lot.

**Comment by Ruturajn** [comment]
Hi,

My latest commit should probably fix, the `SESSION` problem, also. Could you check again?
Thanks

**Comment by voxie12** [comment]
![2022-08-21-131737_532x360_scrot](https://user-images.githubusercontent.com/65469239/185790505-5c077f8b-af16-4fae-89b3-1516a8d39777.png)

almost!

**Comment by Ruturajn** [comment]
Ohk, Thanks for the update, I will rectify it.

**Comment by Ruturajn** [comment]
Hi, this should rectify the problem. Can you confirm 😄?

**Comment by voxie12** [comment]
![2022-08-21-210923_948x513_scrot](https://user-images.githubusercontent.com/65469239/185809055-2e1cdd0d-4f87-41a7-bdd7-7ec41e65a078.png)

Thank you very much.

**Comment by Ruturajn** [comment]
Great. You're welcome. Actually, I should be the one thanking you, because doing this has probably increased the support for the `SESSION` entry. So, Thank You.
