### ISSUE TITLE
README update

### ISSUE THREAD

**Issue by nmb4** [Ruturajn/fetchit#9]
I think the README should contain a hint that custom logos have to be at least 9 lines long (i had to look at the source code to figure out why my logo didn't show up).

**Comment by Ruturajn** [comment]
Hi, Thank you so much for pointing this out. I'll update the README to reflect that. Also, I'm glad you like `fetchit`, and thank you for using it.

**Comment by nmb4** [comment]
Nice! Also thank you for making it, really great alternative to neofetch.
